// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wowulglaoykdvfuqkpxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvd3VsZ2xhb3lrZHZmdXFrcHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzg2MTksImV4cCI6MjA2MjAxNDYxOX0.iourMiXf87JC0wEinlsKHOjFBBE6SZf79IC3dmpago0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);