// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekrvkgvojajchfytjvzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcnZrZ3ZvamFqY2hmeXRqdnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODM2MzgsImV4cCI6MjA3Mjc1OTYzOH0.hUhjd5N20iz_jzbtvMiZwRfhxaTtaIACd2bqMT3tldc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});